export const ALL_CHARACTERS_SUCCESS = "ALL_CHARACTERS_SUCCESS";
export const INITIAL_CHARACTERS_SUCCESS = "INITIAL_CHARACTERS_SUCCESS";

export const ALL_CHARACTERS_FAIL = "ALL_CHARACTERS_FAIL";

export const CHARACTER_DETAILS_SUCCESS = "CHARACTER_DETAILS_SUCCESS";
export const CHARACTERS_DETAILS_FAIL = "CHARACTERS_DETAILS_FAIL";

export const ALL_CHARACTERS_SEARCH_REQUEST = "ALL_CHARACTERS_SEARCH_REQUEST";
export const CLEAR_CHARACTERS = "CLEAR_CHARACTERS";

export const ADMIN_REQUEST = "ADMIN_REQUEST";

export const COMICS_SUCCESS = "COMICS_SUCCESS";
export const EVENTS_SUCCESS = "EVENTS_SUCCESS";
export const STORIES_SUCCESS = "STORIES_SUCCESS";
export const SERIES_SUCCESS = "SERIES_SUCCESS";

export const IS_SEARCH_ACTIVE = "IS_SEARCH_ACTIVE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
